//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.06 at 06:06:55 PM CET 
//


package ftn.xml.ServisPoverenik.model.resenje;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zaglavlje">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="naziv_resenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="broj_resenja">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;pattern value="\d{3}-\d{2}-\d{4}\/\d{4}-\d{2}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="datum_resenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="sadrzaj">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="uvod">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="podnosilac" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="naziv_ustanove" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="adresa_ustanove" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="datum_zalbe" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="zakon">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="clan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="stav" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="tacka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="naziv_zakona" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="doneto_resenje">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="odluka" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="obrazlozenje">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="trazilac_informacija" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="datum_podnosenja_zalbe" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                             &lt;element name="razlog_zalbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="postupak_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="odluka_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="taksa" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="poverenik" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "resenje")
@NoArgsConstructor
@AllArgsConstructor
@Data
public class Resenje {

    @XmlElementRefs({
        @XmlElementRef(name = "poverenik", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
        @XmlElementRef(name = "zaglavlje", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
        @XmlElementRef(name = "sadrzaj", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Resenje.Zaglavlje }{@code >}
     * {@link JAXBElement }{@code <}{@link Resenje.Sadrzaj }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link String }
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="uvod">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="podnosilac" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="naziv_ustanove" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="adresa_ustanove" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="datum_zalbe" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="zakon">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="clan" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="stav" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="tacka" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="naziv_zakona" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="doneto_resenje">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="odluka" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="obrazlozenje">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="trazilac_informacija" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="datum_podnosenja_zalbe" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *                   &lt;element name="razlog_zalbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="postupak_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="odluka_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="taksa" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    @NoArgsConstructor
    @AllArgsConstructor
    @Data
    public static class Sadrzaj {

        @XmlElementRefs({
            @XmlElementRef(name = "doneto_resenje", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
            @XmlElementRef(name = "uvod", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
            @XmlElementRef(name = "obrazlozenje", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class)
        })
        @XmlMixed
        protected List<Serializable> content;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link Resenje.Sadrzaj.Uvod }{@code >}
         * {@link JAXBElement }{@code <}{@link Resenje.Sadrzaj.Obrazlozenje }{@code >}
         * {@link JAXBElement }{@code <}{@link Resenje.Sadrzaj.DonetoResenje }{@code >}
         * {@link String }
         * 
         * 
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="odluka" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        @NoArgsConstructor
        @AllArgsConstructor
        @Data
        public static class DonetoResenje {

            @XmlElementRefs({
                @XmlElementRef(name = "odluka", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                @XmlElementRef(name = "tekst", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class)
            })
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link String }
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="trazilac_informacija" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="datum_podnosenja_zalbe" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="razlog_zalbe" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="postupak_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="odluka_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="taksa" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        @NoArgsConstructor
        @AllArgsConstructor
        @Data
        public static class Obrazlozenje {

            @XmlElementRefs({
                @XmlElementRef(name = "odluka_organa", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                @XmlElementRef(name = "trazilac_informacija", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                @XmlElementRef(name = "taksa", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                @XmlElementRef(name = "datum_podnosenja_zalbe", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                @XmlElementRef(name = "razlog_zalbe", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                @XmlElementRef(name = "postupak_organa", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class)
            })
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}
             * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link String }
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="podnosilac" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="naziv_ustanove" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="adresa_ustanove" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="datum_zalbe" type="{http://www.w3.org/2001/XMLSchema}date"/>
         *         &lt;element name="zakon">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="clan" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="stav" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="tacka" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="naziv_zakona" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        @NoArgsConstructor
        @AllArgsConstructor
        @Data
        public static class Uvod {

            @XmlElementRefs({
                @XmlElementRef(name = "naziv_ustanove", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                @XmlElementRef(name = "adresa_ustanove", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                @XmlElementRef(name = "podnosilac", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                @XmlElementRef(name = "zakon", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                @XmlElementRef(name = "naziv_organa", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                @XmlElementRef(name = "datum_zalbe", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class)
            })
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link Resenje.Sadrzaj.Uvod.Zakon }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
             * {@link String }
             * 
             * 
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="clan" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="stav" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="tacka" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="naziv_zakona" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "content"
            })
            @NoArgsConstructor
            @AllArgsConstructor
            @Data
            public static class Zakon {

                @XmlElementRefs({
                    @XmlElementRef(name = "clan", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                    @XmlElementRef(name = "stav", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                    @XmlElementRef(name = "tacka", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
                    @XmlElementRef(name = "naziv_zakona", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class)
                })
                @XmlMixed
                protected List<Serializable> content;

                /**
                 * Gets the value of the content property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the content property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getContent().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link String }
                 * 
                 * 
                 */
                public List<Serializable> getContent() {
                    if (content == null) {
                        content = new ArrayList<Serializable>();
                    }
                    return this.content;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="naziv_resenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="broj_resenja">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;pattern value="\d{3}-\d{2}-\d{4}\/\d{4}-\d{2}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="datum_resenja" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    @NoArgsConstructor
    @AllArgsConstructor
    @Data
    public static class Zaglavlje {

        @XmlElementRefs({
            @XmlElementRef(name = "datum_resenja", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
            @XmlElementRef(name = "naziv_resenja", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class),
            @XmlElementRef(name = "broj_resenja", namespace = "http://www.ftn.uns.ac.rs/resenje", type = JAXBElement.class)
        })
        @XmlMixed
        protected List<Serializable> content;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link String }
         * 
         * 
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }

    }

}
