//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 10:53:02 PM CET 
//


package ftn.xml.ServisOrganVlasti.model.obavestenje;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.obavestenje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ObavestenjeUvidDatumUvida_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "datum_uvida");
    private final static QName _ObavestenjeUvidAdresaUvida_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "adresa_uvida");
    private final static QName _ObavestenjeUvidKancelarija_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "kancelarija");
    private final static QName _ObavestenjeUvidVremeUvida_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "vreme_uvida");
    private final static QName _ObavestenjeKopijaUplatnica_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "uplatnica");
    private final static QName _ObavestenjeKopijaIzradaKopije_QNAME = new QName("http://www.ftn.uns.ac.rs/obavestenje", "izrada_kopije");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.obavestenje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Obavestenje }
     * 
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link TUplatnica }
     * 
     */
    public TUplatnica createTUplatnica() {
        return new TUplatnica();
    }

    /**
     * Create an instance of {@link Obavestenje.Informacije }
     * 
     */
    public Obavestenje.Informacije createObavestenjeInformacije() {
        return new Obavestenje.Informacije();
    }

    /**
     * Create an instance of {@link Obavestenje.TrazenaInformacija }
     * 
     */
    public Obavestenje.TrazenaInformacija createObavestenjeTrazenaInformacija() {
        return new Obavestenje.TrazenaInformacija();
    }

    /**
     * Create an instance of {@link Obavestenje.Posedovanje }
     * 
     */
    public Obavestenje.Posedovanje createObavestenjePosedovanje() {
        return new Obavestenje.Posedovanje();
    }

    /**
     * Create an instance of {@link Obavestenje.Uvid }
     * 
     */
    public Obavestenje.Uvid createObavestenjeUvid() {
        return new Obavestenje.Uvid();
    }

    /**
     * Create an instance of {@link Obavestenje.Kopija }
     * 
     */
    public Obavestenje.Kopija createObavestenjeKopija() {
        return new Obavestenje.Kopija();
    }

    /**
     * Create an instance of {@link Obavestenje.Dostavljanje }
     * 
     */
    public Obavestenje.Dostavljanje createObavestenjeDostavljanje() {
        return new Obavestenje.Dostavljanje();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TKopija }
     * 
     */
    public TKopija createTKopija() {
        return new TKopija();
    }

    /**
     * Create an instance of {@link TUplatnica.PodaciOUplati }
     * 
     */
    public TUplatnica.PodaciOUplati createTUplatnicaPodaciOUplati() {
        return new TUplatnica.PodaciOUplati();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "datum_uvida", scope = Obavestenje.Uvid.class)
    public JAXBElement<XMLGregorianCalendar> createObavestenjeUvidDatumUvida(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ObavestenjeUvidDatumUvida_QNAME, XMLGregorianCalendar.class, Obavestenje.Uvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "adresa_uvida", scope = Obavestenje.Uvid.class)
    public JAXBElement<TAdresa> createObavestenjeUvidAdresaUvida(TAdresa value) {
        return new JAXBElement<TAdresa>(_ObavestenjeUvidAdresaUvida_QNAME, TAdresa.class, Obavestenje.Uvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "kancelarija", scope = Obavestenje.Uvid.class)
    public JAXBElement<String> createObavestenjeUvidKancelarija(String value) {
        return new JAXBElement<String>(_ObavestenjeUvidKancelarija_QNAME, String.class, Obavestenje.Uvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "vreme_uvida", scope = Obavestenje.Uvid.class)
    public JAXBElement<XMLGregorianCalendar> createObavestenjeUvidVremeUvida(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ObavestenjeUvidVremeUvida_QNAME, XMLGregorianCalendar.class, Obavestenje.Uvid.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TUplatnica }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "uplatnica", scope = Obavestenje.Kopija.class)
    public JAXBElement<TUplatnica> createObavestenjeKopijaUplatnica(TUplatnica value) {
        return new JAXBElement<TUplatnica>(_ObavestenjeKopijaUplatnica_QNAME, TUplatnica.class, Obavestenje.Kopija.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TKopija }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/obavestenje", name = "izrada_kopije", scope = Obavestenje.Kopija.class)
    public JAXBElement<TKopija> createObavestenjeKopijaIzradaKopije(TKopija value) {
        return new JAXBElement<TKopija>(_ObavestenjeKopijaIzradaKopije_QNAME, TKopija.class, Obavestenje.Kopija.class, value);
    }

}
