//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.12 at 12:19:41 AM CET 
//


package ftn.xml.ServisOrganVlasti.model.zalbanacutanje;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.zalbanacutanje package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ZalbaCutanjeMestoIDatumDatumZalbe_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "datum_zalbe");
    private final static QName _ZalbaCutanjeMestoIDatumMesto_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "mesto");
    private final static QName _ZalbaCutanjeSadrzajRazloziPodnsenjaTipoviRazloga_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "tipovi_razloga");
    private final static QName _TRazlogTipRazloga_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "tip_razloga");
    private final static QName _ZalbaCutanjeZaglavljePrimalac_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "primalac");
    private final static QName _ZalbaCutanjeSadrzajIzjava_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "izjava");
    private final static QName _ZalbaCutanjeSadrzajRazloziPodnsenja_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "razlozi_podnsenja");
    private final static QName _ZalbaCutanjeSadrzajPredmet_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "predmet");
    private final static QName _ZalbaCutanjeSadrzajIzjavaPodaciOZahtevu_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "podaci_o_zahtevu");
    private final static QName _ZalbaCutanjeSadrzajIzjavaDatumPodnosenja_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "datum_podnosenja");
    private final static QName _ZalbaCutanjeZaglavljePrimalacAdresaPrimaoca_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "adresa_primaoca");
    private final static QName _ZalbaCutanjeZaglavljePrimalacNazivPrimaoca_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "naziv_primaoca");
    private final static QName _ZalbaCutanjeSadrzajPredmetNazivOrgana_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "naziv_organa");
    private final static QName _ZalbaCutanjeSadrzajPredmetNazivPredmeta_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "naziv_predmeta");
    private final static QName _ZalbaCutanjePodnosilacPotpis_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "potpis");
    private final static QName _ZalbaCutanjePodnosilacPodnosilacTuzbe_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbanacutanje", "podnosilac_tuzbe");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.zalbanacutanje
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaCutanje }
     * 
     */
    public ZalbaCutanje createZalbaCutanje() {
        return new ZalbaCutanje();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.Sadrzaj }
     * 
     */
    public ZalbaCutanje.Sadrzaj createZalbaCutanjeSadrzaj() {
        return new ZalbaCutanje.Sadrzaj();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.Sadrzaj.Izjava }
     * 
     */
    public ZalbaCutanje.Sadrzaj.Izjava createZalbaCutanjeSadrzajIzjava() {
        return new ZalbaCutanje.Sadrzaj.Izjava();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.Sadrzaj.Predmet }
     * 
     */
    public ZalbaCutanje.Sadrzaj.Predmet createZalbaCutanjeSadrzajPredmet() {
        return new ZalbaCutanje.Sadrzaj.Predmet();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.Zaglavlje }
     * 
     */
    public ZalbaCutanje.Zaglavlje createZalbaCutanjeZaglavlje() {
        return new ZalbaCutanje.Zaglavlje();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.Podnosilac }
     * 
     */
    public ZalbaCutanje.Podnosilac createZalbaCutanjePodnosilac() {
        return new ZalbaCutanje.Podnosilac();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.MestoIDatum }
     * 
     */
    public ZalbaCutanje.MestoIDatum createZalbaCutanjeMestoIDatum() {
        return new ZalbaCutanje.MestoIDatum();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TRazlog }
     * 
     */
    public TRazlog createTRazlog() {
        return new TRazlog();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.Sadrzaj.RazloziPodnsenja }
     * 
     */
    public ZalbaCutanje.Sadrzaj.RazloziPodnsenja createZalbaCutanjeSadrzajRazloziPodnsenja() {
        return new ZalbaCutanje.Sadrzaj.RazloziPodnsenja();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.Sadrzaj.Izjava.PodaciOZahtevu }
     * 
     */
    public ZalbaCutanje.Sadrzaj.Izjava.PodaciOZahtevu createZalbaCutanjeSadrzajIzjavaPodaciOZahtevu() {
        return new ZalbaCutanje.Sadrzaj.Izjava.PodaciOZahtevu();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.Sadrzaj.Predmet.NazivOrgana }
     * 
     */
    public ZalbaCutanje.Sadrzaj.Predmet.NazivOrgana createZalbaCutanjeSadrzajPredmetNazivOrgana() {
        return new ZalbaCutanje.Sadrzaj.Predmet.NazivOrgana();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.Zaglavlje.Primalac }
     * 
     */
    public ZalbaCutanje.Zaglavlje.Primalac createZalbaCutanjeZaglavljePrimalac() {
        return new ZalbaCutanje.Zaglavlje.Primalac();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "datum_zalbe", scope = ZalbaCutanje.MestoIDatum.class)
    public JAXBElement<XMLGregorianCalendar> createZalbaCutanjeMestoIDatumDatumZalbe(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ZalbaCutanjeMestoIDatumDatumZalbe_QNAME, XMLGregorianCalendar.class, ZalbaCutanje.MestoIDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "mesto", scope = ZalbaCutanje.MestoIDatum.class)
    public JAXBElement<String> createZalbaCutanjeMestoIDatumMesto(String value) {
        return new JAXBElement<String>(_ZalbaCutanjeMestoIDatumMesto_QNAME, String.class, ZalbaCutanje.MestoIDatum.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TRazlog }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "tipovi_razloga", scope = ZalbaCutanje.Sadrzaj.RazloziPodnsenja.class)
    public JAXBElement<TRazlog> createZalbaCutanjeSadrzajRazloziPodnsenjaTipoviRazloga(TRazlog value) {
        return new JAXBElement<TRazlog>(_ZalbaCutanjeSadrzajRazloziPodnsenjaTipoviRazloga_QNAME, TRazlog.class, ZalbaCutanje.Sadrzaj.RazloziPodnsenja.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "tip_razloga", scope = TRazlog.class)
    public JAXBElement<String> createTRazlogTipRazloga(String value) {
        return new JAXBElement<String>(_TRazlogTipRazloga_QNAME, String.class, TRazlog.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaCutanje.Zaglavlje.Primalac }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "primalac", scope = ZalbaCutanje.Zaglavlje.class)
    public JAXBElement<ZalbaCutanje.Zaglavlje.Primalac> createZalbaCutanjeZaglavljePrimalac(ZalbaCutanje.Zaglavlje.Primalac value) {
        return new JAXBElement<ZalbaCutanje.Zaglavlje.Primalac>(_ZalbaCutanjeZaglavljePrimalac_QNAME, ZalbaCutanje.Zaglavlje.Primalac.class, ZalbaCutanje.Zaglavlje.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaCutanje.Sadrzaj.Izjava }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "izjava", scope = ZalbaCutanje.Sadrzaj.class)
    public JAXBElement<ZalbaCutanje.Sadrzaj.Izjava> createZalbaCutanjeSadrzajIzjava(ZalbaCutanje.Sadrzaj.Izjava value) {
        return new JAXBElement<ZalbaCutanje.Sadrzaj.Izjava>(_ZalbaCutanjeSadrzajIzjava_QNAME, ZalbaCutanje.Sadrzaj.Izjava.class, ZalbaCutanje.Sadrzaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaCutanje.Sadrzaj.RazloziPodnsenja }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "razlozi_podnsenja", scope = ZalbaCutanje.Sadrzaj.class)
    public JAXBElement<ZalbaCutanje.Sadrzaj.RazloziPodnsenja> createZalbaCutanjeSadrzajRazloziPodnsenja(ZalbaCutanje.Sadrzaj.RazloziPodnsenja value) {
        return new JAXBElement<ZalbaCutanje.Sadrzaj.RazloziPodnsenja>(_ZalbaCutanjeSadrzajRazloziPodnsenja_QNAME, ZalbaCutanje.Sadrzaj.RazloziPodnsenja.class, ZalbaCutanje.Sadrzaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaCutanje.Sadrzaj.Predmet }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "predmet", scope = ZalbaCutanje.Sadrzaj.class)
    public JAXBElement<ZalbaCutanje.Sadrzaj.Predmet> createZalbaCutanjeSadrzajPredmet(ZalbaCutanje.Sadrzaj.Predmet value) {
        return new JAXBElement<ZalbaCutanje.Sadrzaj.Predmet>(_ZalbaCutanjeSadrzajPredmet_QNAME, ZalbaCutanje.Sadrzaj.Predmet.class, ZalbaCutanje.Sadrzaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaCutanje.Sadrzaj.Izjava.PodaciOZahtevu }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "podaci_o_zahtevu", scope = ZalbaCutanje.Sadrzaj.Izjava.class)
    public JAXBElement<ZalbaCutanje.Sadrzaj.Izjava.PodaciOZahtevu> createZalbaCutanjeSadrzajIzjavaPodaciOZahtevu(ZalbaCutanje.Sadrzaj.Izjava.PodaciOZahtevu value) {
        return new JAXBElement<ZalbaCutanje.Sadrzaj.Izjava.PodaciOZahtevu>(_ZalbaCutanjeSadrzajIzjavaPodaciOZahtevu_QNAME, ZalbaCutanje.Sadrzaj.Izjava.PodaciOZahtevu.class, ZalbaCutanje.Sadrzaj.Izjava.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "datum_podnosenja", scope = ZalbaCutanje.Sadrzaj.Izjava.class)
    public JAXBElement<XMLGregorianCalendar> createZalbaCutanjeSadrzajIzjavaDatumPodnosenja(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_ZalbaCutanjeSadrzajIzjavaDatumPodnosenja_QNAME, XMLGregorianCalendar.class, ZalbaCutanje.Sadrzaj.Izjava.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TAdresa }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "adresa_primaoca", scope = ZalbaCutanje.Zaglavlje.Primalac.class)
    public JAXBElement<TAdresa> createZalbaCutanjeZaglavljePrimalacAdresaPrimaoca(TAdresa value) {
        return new JAXBElement<TAdresa>(_ZalbaCutanjeZaglavljePrimalacAdresaPrimaoca_QNAME, TAdresa.class, ZalbaCutanje.Zaglavlje.Primalac.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "naziv_primaoca", scope = ZalbaCutanje.Zaglavlje.Primalac.class)
    public JAXBElement<String> createZalbaCutanjeZaglavljePrimalacNazivPrimaoca(String value) {
        return new JAXBElement<String>(_ZalbaCutanjeZaglavljePrimalacNazivPrimaoca_QNAME, String.class, ZalbaCutanje.Zaglavlje.Primalac.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaCutanje.Sadrzaj.Predmet.NazivOrgana }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "naziv_organa", scope = ZalbaCutanje.Sadrzaj.Predmet.class)
    public JAXBElement<ZalbaCutanje.Sadrzaj.Predmet.NazivOrgana> createZalbaCutanjeSadrzajPredmetNazivOrgana(ZalbaCutanje.Sadrzaj.Predmet.NazivOrgana value) {
        return new JAXBElement<ZalbaCutanje.Sadrzaj.Predmet.NazivOrgana>(_ZalbaCutanjeSadrzajPredmetNazivOrgana_QNAME, ZalbaCutanje.Sadrzaj.Predmet.NazivOrgana.class, ZalbaCutanje.Sadrzaj.Predmet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "naziv_predmeta", scope = ZalbaCutanje.Sadrzaj.Predmet.class)
    public JAXBElement<String> createZalbaCutanjeSadrzajPredmetNazivPredmeta(String value) {
        return new JAXBElement<String>(_ZalbaCutanjeSadrzajPredmetNazivPredmeta_QNAME, String.class, ZalbaCutanje.Sadrzaj.Predmet.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "potpis", scope = ZalbaCutanje.Podnosilac.class)
    public JAXBElement<String> createZalbaCutanjePodnosilacPotpis(String value) {
        return new JAXBElement<String>(_ZalbaCutanjePodnosilacPotpis_QNAME, String.class, ZalbaCutanje.Podnosilac.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbanacutanje", name = "podnosilac_tuzbe", scope = ZalbaCutanje.Podnosilac.class)
    public JAXBElement<TLice> createZalbaCutanjePodnosilacPodnosilacTuzbe(TLice value) {
        return new JAXBElement<TLice>(_ZalbaCutanjePodnosilacPodnosilacTuzbe_QNAME, TLice.class, ZalbaCutanje.Podnosilac.class, value);
    }

}
