//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.05 at 10:14:54 PM CET 
//


package rs.ac.uns.ftn.zalbanaodluku;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the rs.ac.uns.ftn.zalbanaodluku package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ZalbaNaOdlukuZalbaSadrzajPodaciDatumPodnosenja_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "datum_podnosenja");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajPodaciIme_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "ime");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajPodaciPrezime_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "prezime");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajPodaciDrugiPodaciKontakt_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "drugi_podaci_kontakt");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajBrojResenja_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "broj_resenja");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajParagrafi_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "paragrafi");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajGodina_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "godina");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajNazivOrganaVlasti_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "naziv_organa_vlasti");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajPodnosilacZalbe_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "podnosilac_zalbe");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajPodaci_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "podaci");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajParagrafiParagraf_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "paragraf");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajParagrafiParagrafPodaci_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "paragraf_podaci");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajParagrafiParagrafPodaciDatum_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "datum");
    private final static QName _ZalbaNaOdlukuZalbaSadrzajParagrafiParagrafPodaciRazlog_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "razlog");
    private final static QName _TAdresaPrimaocaBroj_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "broj");
    private final static QName _TAdresaPrimaocaUlica_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "ulica");
    private final static QName _TAdresaPrimaocaGrad_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "grad");
    private final static QName _ZalbaNaOdlukuNapomeneNapomena_QNAME = new QName("http://www.ftn.uns.ac.rs/zalbaNaOdluku", "napomena");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: rs.ac.uns.ftn.zalbanaodluku
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku }
     * 
     */
    public ZalbaNaOdluku createZalbaNaOdluku() {
        return new ZalbaNaOdluku();
    }

    /**
     * Create an instance of {@link TPodnosilacZalbe }
     * 
     */
    public TPodnosilacZalbe createTPodnosilacZalbe() {
        return new TPodnosilacZalbe();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.ZalbaSadrzaj }
     * 
     */
    public ZalbaNaOdluku.ZalbaSadrzaj createZalbaNaOdlukuZalbaSadrzaj() {
        return new ZalbaNaOdluku.ZalbaSadrzaj();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi }
     * 
     */
    public ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi createZalbaNaOdlukuZalbaSadrzajParagrafi() {
        return new ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.Zaglavlje }
     * 
     */
    public ZalbaNaOdluku.Zaglavlje createZalbaNaOdlukuZaglavlje() {
        return new ZalbaNaOdluku.Zaglavlje();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.Napomene }
     * 
     */
    public ZalbaNaOdluku.Napomene createZalbaNaOdlukuNapomene() {
        return new ZalbaNaOdluku.Napomene();
    }

    /**
     * Create an instance of {@link TAdresaPrimaoca }
     * 
     */
    public TAdresaPrimaoca createTAdresaPrimaoca() {
        return new TAdresaPrimaoca();
    }

    /**
     * Create an instance of {@link TAdresa }
     * 
     */
    public TAdresa createTAdresa() {
        return new TAdresa();
    }

    /**
     * Create an instance of {@link TPodnosilacZalbe.Ime }
     * 
     */
    public TPodnosilacZalbe.Ime createTPodnosilacZalbeIme() {
        return new TPodnosilacZalbe.Ime();
    }

    /**
     * Create an instance of {@link TPodnosilacZalbe.Prezime }
     * 
     */
    public TPodnosilacZalbe.Prezime createTPodnosilacZalbePrezime() {
        return new TPodnosilacZalbe.Prezime();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.ZalbaSadrzaj.PodnosilacZalbe }
     * 
     */
    public ZalbaNaOdluku.ZalbaSadrzaj.PodnosilacZalbe createZalbaNaOdlukuZalbaSadrzajPodnosilacZalbe() {
        return new ZalbaNaOdluku.ZalbaSadrzaj.PodnosilacZalbe();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.ZalbaSadrzaj.Podaci }
     * 
     */
    public ZalbaNaOdluku.ZalbaSadrzaj.Podaci createZalbaNaOdlukuZalbaSadrzajPodaci() {
        return new ZalbaNaOdluku.ZalbaSadrzaj.Podaci();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci }
     * 
     */
    public ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci createZalbaNaOdlukuZalbaSadrzajParagrafiParagrafPodaci() {
        return new ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "datum_podnosenja", scope = ZalbaNaOdluku.ZalbaSadrzaj.Podaci.class)
    public JAXBElement<String> createZalbaNaOdlukuZalbaSadrzajPodaciDatumPodnosenja(String value) {
        return new JAXBElement<String>(_ZalbaNaOdlukuZalbaSadrzajPodaciDatumPodnosenja_QNAME, String.class, ZalbaNaOdluku.ZalbaSadrzaj.Podaci.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "ime", scope = ZalbaNaOdluku.ZalbaSadrzaj.Podaci.class)
    public JAXBElement<String> createZalbaNaOdlukuZalbaSadrzajPodaciIme(String value) {
        return new JAXBElement<String>(_ZalbaNaOdlukuZalbaSadrzajPodaciIme_QNAME, String.class, ZalbaNaOdluku.ZalbaSadrzaj.Podaci.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "prezime", scope = ZalbaNaOdluku.ZalbaSadrzaj.Podaci.class)
    public JAXBElement<String> createZalbaNaOdlukuZalbaSadrzajPodaciPrezime(String value) {
        return new JAXBElement<String>(_ZalbaNaOdlukuZalbaSadrzajPodaciPrezime_QNAME, String.class, ZalbaNaOdluku.ZalbaSadrzaj.Podaci.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "drugi_podaci_kontakt", scope = ZalbaNaOdluku.ZalbaSadrzaj.Podaci.class)
    public JAXBElement<String> createZalbaNaOdlukuZalbaSadrzajPodaciDrugiPodaciKontakt(String value) {
        return new JAXBElement<String>(_ZalbaNaOdlukuZalbaSadrzajPodaciDrugiPodaciKontakt_QNAME, String.class, ZalbaNaOdluku.ZalbaSadrzaj.Podaci.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "broj_resenja", scope = ZalbaNaOdluku.ZalbaSadrzaj.class)
    public JAXBElement<String> createZalbaNaOdlukuZalbaSadrzajBrojResenja(String value) {
        return new JAXBElement<String>(_ZalbaNaOdlukuZalbaSadrzajBrojResenja_QNAME, String.class, ZalbaNaOdluku.ZalbaSadrzaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "paragrafi", scope = ZalbaNaOdluku.ZalbaSadrzaj.class)
    public JAXBElement<ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi> createZalbaNaOdlukuZalbaSadrzajParagrafi(ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi value) {
        return new JAXBElement<ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi>(_ZalbaNaOdlukuZalbaSadrzajParagrafi_QNAME, ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.class, ZalbaNaOdluku.ZalbaSadrzaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "godina", scope = ZalbaNaOdluku.ZalbaSadrzaj.class)
    public JAXBElement<String> createZalbaNaOdlukuZalbaSadrzajGodina(String value) {
        return new JAXBElement<String>(_ZalbaNaOdlukuZalbaSadrzajGodina_QNAME, String.class, ZalbaNaOdluku.ZalbaSadrzaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "naziv_organa_vlasti", scope = ZalbaNaOdluku.ZalbaSadrzaj.class)
    public JAXBElement<String> createZalbaNaOdlukuZalbaSadrzajNazivOrganaVlasti(String value) {
        return new JAXBElement<String>(_ZalbaNaOdlukuZalbaSadrzajNazivOrganaVlasti_QNAME, String.class, ZalbaNaOdluku.ZalbaSadrzaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaNaOdluku.ZalbaSadrzaj.PodnosilacZalbe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "podnosilac_zalbe", scope = ZalbaNaOdluku.ZalbaSadrzaj.class)
    public JAXBElement<ZalbaNaOdluku.ZalbaSadrzaj.PodnosilacZalbe> createZalbaNaOdlukuZalbaSadrzajPodnosilacZalbe(ZalbaNaOdluku.ZalbaSadrzaj.PodnosilacZalbe value) {
        return new JAXBElement<ZalbaNaOdluku.ZalbaSadrzaj.PodnosilacZalbe>(_ZalbaNaOdlukuZalbaSadrzajPodnosilacZalbe_QNAME, ZalbaNaOdluku.ZalbaSadrzaj.PodnosilacZalbe.class, ZalbaNaOdluku.ZalbaSadrzaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaNaOdluku.ZalbaSadrzaj.Podaci }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "podaci", scope = ZalbaNaOdluku.ZalbaSadrzaj.class)
    public JAXBElement<ZalbaNaOdluku.ZalbaSadrzaj.Podaci> createZalbaNaOdlukuZalbaSadrzajPodaci(ZalbaNaOdluku.ZalbaSadrzaj.Podaci value) {
        return new JAXBElement<ZalbaNaOdluku.ZalbaSadrzaj.Podaci>(_ZalbaNaOdlukuZalbaSadrzajPodaci_QNAME, ZalbaNaOdluku.ZalbaSadrzaj.Podaci.class, ZalbaNaOdluku.ZalbaSadrzaj.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "paragraf", scope = ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.class)
    public JAXBElement<String> createZalbaNaOdlukuZalbaSadrzajParagrafiParagraf(String value) {
        return new JAXBElement<String>(_ZalbaNaOdlukuZalbaSadrzajParagrafiParagraf_QNAME, String.class, ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "paragraf_podaci", scope = ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.class)
    public JAXBElement<ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci> createZalbaNaOdlukuZalbaSadrzajParagrafiParagrafPodaci(ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci value) {
        return new JAXBElement<ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci>(_ZalbaNaOdlukuZalbaSadrzajParagrafiParagrafPodaci_QNAME, ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci.class, ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "datum", scope = ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci.class)
    public JAXBElement<String> createZalbaNaOdlukuZalbaSadrzajParagrafiParagrafPodaciDatum(String value) {
        return new JAXBElement<String>(_ZalbaNaOdlukuZalbaSadrzajParagrafiParagrafPodaciDatum_QNAME, String.class, ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "razlog", scope = ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci.class)
    public JAXBElement<String> createZalbaNaOdlukuZalbaSadrzajParagrafiParagrafPodaciRazlog(String value) {
        return new JAXBElement<String>(_ZalbaNaOdlukuZalbaSadrzajParagrafiParagrafPodaciRazlog_QNAME, String.class, ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "broj", scope = TAdresaPrimaoca.class)
    public JAXBElement<String> createTAdresaPrimaocaBroj(String value) {
        return new JAXBElement<String>(_TAdresaPrimaocaBroj_QNAME, String.class, TAdresaPrimaoca.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "ulica", scope = TAdresaPrimaoca.class)
    public JAXBElement<String> createTAdresaPrimaocaUlica(String value) {
        return new JAXBElement<String>(_TAdresaPrimaocaUlica_QNAME, String.class, TAdresaPrimaoca.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "grad", scope = TAdresaPrimaoca.class)
    public JAXBElement<String> createTAdresaPrimaocaGrad(String value) {
        return new JAXBElement<String>(_TAdresaPrimaocaGrad_QNAME, String.class, TAdresaPrimaoca.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", name = "napomena", scope = ZalbaNaOdluku.Napomene.class)
    public JAXBElement<String> createZalbaNaOdlukuNapomeneNapomena(String value) {
        return new JAXBElement<String>(_ZalbaNaOdlukuNapomeneNapomena_QNAME, String.class, ZalbaNaOdluku.Napomene.class, value);
    }

}
