//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.02.05 at 10:14:54 PM CET
//
package ftn.xml.ServisPoverenik.model.zalbanaodluku;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zaglavlje">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="primalac" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="adresa_primaoca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="zalba_sadrzaj">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="podnosilac_zalbe">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;extension base="{http://www.ftn.uns.ac.rs/zalbaNaOdluku}TPodnosilacZalbe">
 *                           &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/extension>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="naziv_organa_vlasti" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="broj_resenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="godina" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="paragrafi">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="paragraf_podaci">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="paragraf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="paragraf" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="podaci">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="drugi_podaci_kontakt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="napomene">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="napomena" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="napomena" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "zaglavlje",
        "zalbaSadrzaj",
        "napomene"
})
@XmlRootElement(name = "zalba_na_odluku")
public class ZalbaNaOdluku {

    @XmlElement(required = true)
    protected ZalbaNaOdluku.Zaglavlje zaglavlje;
    @XmlElement(name = "zalba_sadrzaj", required = true)
    protected ZalbaNaOdluku.ZalbaSadrzaj zalbaSadrzaj;
    @XmlElement(required = true)
    protected ZalbaNaOdluku.Napomene napomene;

    /**
     * Gets the value of the zaglavlje property.
     *
     * @return
     *     possible object is
     *     {@link ZalbaNaOdluku.Zaglavlje }
     *
     */
    public ZalbaNaOdluku.Zaglavlje getZaglavlje() {
        return zaglavlje;
    }

    /**
     * Sets the value of the zaglavlje property.
     *
     * @param value
     *     allowed object is
     *     {@link ZalbaNaOdluku.Zaglavlje }
     *
     */
    public void setZaglavlje(ZalbaNaOdluku.Zaglavlje value) {
        this.zaglavlje = value;
    }

    /**
     * Gets the value of the zalbaSadrzaj property.
     *
     * @return
     *     possible object is
     *     {@link ZalbaNaOdluku.ZalbaSadrzaj }
     *
     */
    public ZalbaNaOdluku.ZalbaSadrzaj getZalbaSadrzaj() {
        return zalbaSadrzaj;
    }

    /**
     * Sets the value of the zalbaSadrzaj property.
     *
     * @param value
     *     allowed object is
     *     {@link ZalbaNaOdluku.ZalbaSadrzaj }
     *
     */
    public void setZalbaSadrzaj(ZalbaNaOdluku.ZalbaSadrzaj value) {
        this.zalbaSadrzaj = value;
    }

    /**
     * Gets the value of the napomene property.
     *
     * @return
     *     possible object is
     *     {@link ZalbaNaOdluku.Napomene }
     *
     */
    public ZalbaNaOdluku.Napomene getNapomene() {
        return napomene;
    }

    /**
     * Sets the value of the napomene property.
     *
     * @param value
     *     allowed object is
     *     {@link ZalbaNaOdluku.Napomene }
     *
     */
    public void setNapomene(ZalbaNaOdluku.Napomene value) {
        this.napomene = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="napomena" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="napomena" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "content"
    })
    public static class Napomene {

        @XmlElementRef(name = "napomena", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class)
        @XmlMixed
        protected List<Serializable> content;

        /**
         * Gets the value of the content property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link String }
         *
         *
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="primalac" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="adresa_primaoca" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "naslov",
            "primalac",
            "adresaPrimaoca"
    })
    public static class Zaglavlje {

        @XmlElement(required = true)
        protected String naslov;
        @XmlElement(required = true)
        protected String primalac;
        @XmlElement(name = "adresa_primaoca", required = true)
        protected String adresaPrimaoca;

        /**
         * Gets the value of the naslov property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getNaslov() {
            return naslov;
        }

        /**
         * Sets the value of the naslov property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setNaslov(String value) {
            this.naslov = value;
        }

        /**
         * Gets the value of the primalac property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPrimalac() {
            return primalac;
        }

        /**
         * Sets the value of the primalac property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPrimalac(String value) {
            this.primalac = value;
        }

        /**
         * Gets the value of the adresaPrimaoca property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getAdresaPrimaoca() {
            return adresaPrimaoca;
        }

        /**
         * Sets the value of the adresaPrimaoca property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setAdresaPrimaoca(String value) {
            this.adresaPrimaoca = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="podnosilac_zalbe">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;extension base="{http://www.ftn.uns.ac.rs/zalbaNaOdluku}TPodnosilacZalbe">
     *                 &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/extension>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="naziv_organa_vlasti" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="broj_resenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="godina" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="paragrafi">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="paragraf_podaci">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="paragraf" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="paragraf" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="podaci">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="drugi_podaci_kontakt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
            "content"
    })
    public static class ZalbaSadrzaj {

        @XmlElementRefs({
                @XmlElementRef(name = "paragrafi", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class),
                @XmlElementRef(name = "broj_resenja", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class),
                @XmlElementRef(name = "podnosilac_zalbe", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class),
                @XmlElementRef(name = "podaci", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class),
                @XmlElementRef(name = "godina", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class),
                @XmlElementRef(name = "naziv_organa_vlasti", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class)
        })
        @XmlMixed
        protected List<Serializable> content;

        /**
         * Gets the value of the content property.
         *
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         *
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         *
         *
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link ZalbaNaOdluku.ZalbaSadrzaj.PodnosilacZalbe }{@code >}
         * {@link JAXBElement }{@code <}{@link ZalbaNaOdluku.ZalbaSadrzaj.Podaci }{@code >}
         * {@link String }
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         *
         *
         */
        public List<Serializable> getContent() {
            if (content == null) {
                content = new ArrayList<Serializable>();
            }
            return this.content;
        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="paragraf_podaci">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="paragraf" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="paragraf" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "content"
        })
        public static class Paragrafi {

            @XmlElementRefs({
                    @XmlElementRef(name = "paragraf_podaci", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class, required = false),
                    @XmlElementRef(name = "paragraf", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class, required = false)
            })
            protected List<JAXBElement<?>> content;

            /**
             * Gets the rest of the content model.
             *
             * <p>
             * You are getting this "catch-all" property because of the following reason:
             * The field name "Paragraf" is used by two different parts of a schema. See:
             * line 45 of file:/D:/Users/Hp%20Zbook%2015/Desktop/xml-projekat-2020/ServisPoverenik/src/main/java/ftn/xml/ServisPoverenik/model/xd/zalbanaodluku-schema.xsd
             * line 44 of file:/D:/Users/Hp%20Zbook%2015/Desktop/xml-projekat-2020/ServisPoverenik/src/main/java/ftn/xml/ServisPoverenik/model/xd/zalbanaodluku-schema.xsd
             * <p>
             * To get rid of this property, apply a property customization to one
             * of both of the following declarations to change their names:
             * Gets the value of the content property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link ZalbaNaOdluku.ZalbaSadrzaj.Paragrafi.ParagrafPodaci }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             *
             *
             */
            public List<JAXBElement<?>> getContent() {
                if (content == null) {
                    content = new ArrayList<JAXBElement<?>>();
                }
                return this.content;
            }


            /**
             * <p>Java class for anonymous complex type.
             *
             * <p>The following schema fragment specifies the expected content contained within this class.
             *
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             *
             *
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                    "content"
            })
            public static class ParagrafPodaci {

                @XmlElementRefs({
                        @XmlElementRef(name = "datum", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class),
                        @XmlElementRef(name = "razlog", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class)
                })
                @XmlMixed
                protected List<Serializable> content;

                /**
                 * Gets the value of the content property.
                 *
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the content property.
                 *
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getContent().add(newItem);
                 * </pre>
                 *
                 *
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link JAXBElement }{@code <}{@link String }{@code >}
                 * {@link String }
                 *
                 *
                 */
                public List<Serializable> getContent() {
                    if (content == null) {
                        content = new ArrayList<Serializable>();
                    }
                    return this.content;
                }

            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="ime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="prezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="datum_podnosenja" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="drugi_podaci_kontakt" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
                "content"
        })
        public static class Podaci {

            @XmlElementRefs({
                    @XmlElementRef(name = "datum_podnosenja", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class),
                    @XmlElementRef(name = "prezime", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class),
                    @XmlElementRef(name = "ime", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class),
                    @XmlElementRef(name = "drugi_podaci_kontakt", namespace = "http://www.ftn.uns.ac.rs/zalbaNaOdluku", type = JAXBElement.class)
            })
            @XmlMixed
            protected List<Serializable> content;

            /**
             * Gets the value of the content property.
             *
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             *
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             *
             *
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link String }
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             *
             *
             */
            public List<Serializable> getContent() {
                if (content == null) {
                    content = new ArrayList<Serializable>();
                }
                return this.content;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         *
         * <p>The following schema fragment specifies the expected content contained within this class.
         *
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;extension base="{http://www.ftn.uns.ac.rs/zalbaNaOdluku}TPodnosilacZalbe">
         *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/extension>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         *
         *
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class PodnosilacZalbe
                extends TPodnosilacZalbe
        {

            @XmlAttribute(name = "about")
            protected String about;

            /**
             * Gets the value of the about property.
             *
             * @return
             *     possible object is
             *     {@link String }
             *
             */
            public String getAbout() {
                return about;
            }

            /**
             * Sets the value of the about property.
             *
             * @param value
             *     allowed object is
             *     {@link String }
             *
             */
            public void setAbout(String value) {
                this.about = value;
            }

        }

    }

}