//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.11 at 11:35:49 AM CET 
//


package ftn.xml.ServisOrganVlasti.model.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TDatum complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TDatum">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tekst_dan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dan" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="mesec" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="godina" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="tekst_godina" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TDatum", propOrder = {
    "tekstDan",
    "dan",
    "mesec",
    "godina",
    "tekstGodina"
})
public class TDatum {

    @XmlElement(name = "tekst_dan", required = true)
    protected String tekstDan;
    @XmlElement(required = true)
    protected String dan;
    @XmlElement(required = true)
    protected String mesec;
    @XmlElement(required = true)
    protected String godina;
    @XmlElement(name = "tekst_godina", required = true)
    protected String tekstGodina;

    /**
     * Gets the value of the tekstDan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTekstDan() {
        return tekstDan;
    }

    /**
     * Sets the value of the tekstDan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTekstDan(String value) {
        this.tekstDan = value;
    }

    /**
     * Gets the value of the dan property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDan() {
        return dan;
    }

    /**
     * Sets the value of the dan property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDan(String value) {
        this.dan = value;
    }

    /**
     * Gets the value of the mesec property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMesec() {
        return mesec;
    }

    /**
     * Sets the value of the mesec property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMesec(String value) {
        this.mesec = value;
    }

    /**
     * Gets the value of the godina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGodina() {
        return godina;
    }

    /**
     * Sets the value of the godina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGodina(String value) {
        this.godina = value;
    }

    /**
     * Gets the value of the tekstGodina property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTekstGodina() {
        return tekstGodina;
    }

    /**
     * Sets the value of the tekstGodina property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTekstGodina(String value) {
        this.tekstGodina = value;
    }

}
