//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.11 at 11:35:49 AM CET 
//


package ftn.xml.ServisOrganVlasti.model.zahtev;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zaglavlje">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="organ">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="sediste_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="naslov" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="sadrzaj">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                   &lt;element name="tipovi_zahteva">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="tip_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="tip_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="tip_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="tip_zahteva_dostava">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
 *                                       &lt;element name="vrste_dostave" type="{http://www.ftn.uns.ac.rs/zahtev}TDostava"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="informacije_o_zahtevu" type="{http://www.ftn.uns.ac.rs/zahtev}TInformacijeOZahtevu"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="informacije_trazioca">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ime">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:ime" />
 *                           &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="prezime">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:prezime" />
 *                           &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="adresa">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:adresa" />
 *                           &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="kontakt_podaci">
 *                     &lt;complexType>
 *                       &lt;simpleContent>
 *                         &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                           &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:kontakt" />
 *                           &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
 *                         &lt;/extension>
 *                       &lt;/simpleContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="about" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="http://www.ftn.uns.ac.rs/rdf/resenje/trazilac" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="mesto_i_datum">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="datum" type="{http://www.ftn.uns.ac.rs/zahtev}TDatum"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="http://www.ftn.uns.ac.rs/rdf/resenje/mestoDatumZahteva" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fusnote">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="fusnota" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fusnota" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="fusnota" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zaglavlje",
    "naslov",
    "sadrzaj",
    "informacijeTrazioca",
    "mestoIDatum",
    "fusnote"
})
@XmlRootElement(name = "zahtev_za_pristup_informacijama")
public class ZahtevZaPristupInformacijama {

    @XmlElement(required = true)
    protected ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Zaglavlje zaglavlje;
    @XmlElement(required = true)
    protected String naslov;
    @XmlElement(required = true)
    protected ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Sadrzaj sadrzaj;
    @XmlElement(name = "informacije_trazioca", required = true)
    protected ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca informacijeTrazioca;
    @XmlElement(name = "mesto_i_datum", required = true)
    protected ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.MestoIDatum mestoIDatum;
    @XmlElement(required = true)
    protected ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Fusnote fusnote;

    /**
     * Gets the value of the zaglavlje property.
     * 
     * @return
     *     possible object is
     *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Zaglavlje }
     *     
     */
    public ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Zaglavlje getZaglavlje() {
        return zaglavlje;
    }

    /**
     * Sets the value of the zaglavlje property.
     * 
     * @param value
     *     allowed object is
     *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Zaglavlje }
     *     
     */
    public void setZaglavlje(ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Zaglavlje value) {
        this.zaglavlje = value;
    }

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the sadrzaj property.
     * 
     * @return
     *     possible object is
     *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Sadrzaj }
     *     
     */
    public ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Sadrzaj getSadrzaj() {
        return sadrzaj;
    }

    /**
     * Sets the value of the sadrzaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Sadrzaj }
     *     
     */
    public void setSadrzaj(ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Sadrzaj value) {
        this.sadrzaj = value;
    }

    /**
     * Gets the value of the informacijeTrazioca property.
     * 
     * @return
     *     possible object is
     *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca }
     *     
     */
    public ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca getInformacijeTrazioca() {
        return informacijeTrazioca;
    }

    /**
     * Sets the value of the informacijeTrazioca property.
     * 
     * @param value
     *     allowed object is
     *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca }
     *     
     */
    public void setInformacijeTrazioca(ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca value) {
        this.informacijeTrazioca = value;
    }

    /**
     * Gets the value of the mestoIDatum property.
     * 
     * @return
     *     possible object is
     *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.MestoIDatum }
     *
     */
    public ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.MestoIDatum getMestoIDatum() {
        return mestoIDatum;
    }

    /**
     * Sets the value of the mestoIDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.MestoIDatum }
     *     
     */
    public void setMestoIDatum(ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.MestoIDatum value) {
        this.mestoIDatum = value;
    }

    /**
     * Gets the value of the fusnote property.
     * 
     * @return
     *     possible object is
     *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Fusnote }
     *     
     */
    public ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Fusnote getFusnote() {
        return fusnote;
    }

    /**
     * Sets the value of the fusnote property.
     * 
     * @param value
     *     allowed object is
     *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Fusnote }
     *     
     */
    public void setFusnote(ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Fusnote value) {
        this.fusnote = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="fusnota" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fusnota" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="fusnota" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Fusnote {

        @XmlElementRef(name = "fusnota", namespace = "http://www.ftn.uns.ac.rs/zahtev", type = JAXBElement.class, required = false)
        protected List<JAXBElement<String>> content;

        /**
         * Gets the rest of the content model. 
         * 
         * <p>
         * You are getting this "catch-all" property because of the following reason: 
         * The field name "Fusnota" is used by two different parts of a schema. See: 
         * line 123 of file:/D:/Users/Hp%20Zbook%2015/Desktop/xml-projekat-2020/xml-documents/zahtev.xsd
         * line 121 of file:/D:/Users/Hp%20Zbook%2015/Desktop/xml-projekat-2020/xml-documents/zahtev.xsd
         * <p>
         * To get rid of this property, apply a property customization to one 
         * of both of the following declarations to change their names: 
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * 
         * 
         */
        public List<JAXBElement<String>> getContent() {
            if (content == null) {
                content = new ArrayList<JAXBElement<String>>();
            }
            return this.content;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ime">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:ime" />
     *                 &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="prezime">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:prezime" />
     *                 &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="adresa">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:adresa" />
     *                 &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="kontakt_podaci">
     *           &lt;complexType>
     *             &lt;simpleContent>
     *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *                 &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:kontakt" />
     *                 &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
     *               &lt;/extension>
     *             &lt;/simpleContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="potpis" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *       &lt;attribute name="about" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="http://www.ftn.uns.ac.rs/rdf/resenje/trazilac" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ime",
        "prezime",
        "adresa",
        "kontaktPodaci",
        "potpis"
    })
    public static class InformacijeTrazioca {

        @XmlElement(required = true)
        protected ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Ime ime;
        @XmlElement(required = true)
        protected ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Prezime prezime;
        @XmlElement(required = true)
        protected ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Adresa adresa;
        @XmlElement(name = "kontakt_podaci", required = true)
        protected ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.KontaktPodaci kontaktPodaci;
        @XmlElement(required = true)
        protected String potpis;
        @XmlAttribute(name = "about", required = true)
        protected String about;

        /**
         * Gets the value of the ime property.
         * 
         * @return
         *     possible object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Ime }
         *     
         */
        public ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Ime getIme() {
            return ime;
        }

        /**
         * Sets the value of the ime property.
         * 
         * @param value
         *     allowed object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Ime }
         *     
         */
        public void setIme(ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Ime value) {
            this.ime = value;
        }

        /**
         * Gets the value of the prezime property.
         * 
         * @return
         *     possible object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Prezime }
         *     
         */
        public ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Prezime getPrezime() {
            return prezime;
        }

        /**
         * Sets the value of the prezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Prezime }
         *     
         */
        public void setPrezime(ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Prezime value) {
            this.prezime = value;
        }

        /**
         * Gets the value of the adresa property.
         * 
         * @return
         *     possible object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Adresa }
         *     
         */
        public ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Adresa getAdresa() {
            return adresa;
        }

        /**
         * Sets the value of the adresa property.
         * 
         * @param value
         *     allowed object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Adresa }
         *     
         */
        public void setAdresa(ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.Adresa value) {
            this.adresa = value;
        }

        /**
         * Gets the value of the kontaktPodaci property.
         * 
         * @return
         *     possible object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.KontaktPodaci }
         *     
         */
        public ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.KontaktPodaci getKontaktPodaci() {
            return kontaktPodaci;
        }

        /**
         * Sets the value of the kontaktPodaci property.
         * 
         * @param value
         *     allowed object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.KontaktPodaci }
         *     
         */
        public void setKontaktPodaci(ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.InformacijeTrazioca.KontaktPodaci value) {
            this.kontaktPodaci = value;
        }

        /**
         * Gets the value of the potpis property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPotpis() {
            return potpis;
        }

        /**
         * Sets the value of the potpis property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPotpis(String value) {
            this.potpis = value;
        }

        /**
         * Gets the value of the about property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAbout() {
            if (about == null) {
                return "http://www.ftn.uns.ac.rs/rdf/resenje/trazilac";
            } else {
                return about;
            }
        }

        /**
         * Sets the value of the about property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAbout(String value) {
            this.about = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:adresa" />
         *       &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Adresa {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property", required = true)
            protected String property;
            @XmlAttribute(name = "datatype", required = true)
            protected String datatype;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:adresa";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                if (datatype == null) {
                    return "xsi:string";
                } else {
                    return datatype;
                }
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:ime" />
         *       &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Ime {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property", required = true)
            protected String property;
            @XmlAttribute(name = "datatype", required = true)
            protected String datatype;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:ime";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                if (datatype == null) {
                    return "xsi:string";
                } else {
                    return datatype;
                }
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:kontakt" />
         *       &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class KontaktPodaci {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property", required = true)
            protected String property;
            @XmlAttribute(name = "datatype", required = true)
            protected String datatype;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:kontakt";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                if (datatype == null) {
                    return "xsi:string";
                } else {
                    return datatype;
                }
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;simpleContent>
         *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
         *       &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="pred:prezime" />
         *       &lt;attribute name="datatype" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="xsi:string" />
         *     &lt;/extension>
         *   &lt;/simpleContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "value"
        })
        public static class Prezime {

            @XmlValue
            protected String value;
            @XmlAttribute(name = "property", required = true)
            protected String property;
            @XmlAttribute(name = "datatype", required = true)
            protected String datatype;

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

            /**
             * Gets the value of the property property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getProperty() {
                if (property == null) {
                    return "pred:prezime";
                } else {
                    return property;
                }
            }

            /**
             * Sets the value of the property property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setProperty(String value) {
                this.property = value;
            }

            /**
             * Gets the value of the datatype property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDatatype() {
                if (datatype == null) {
                    return "xsi:string";
                } else {
                    return datatype;
                }
            }

            /**
             * Sets the value of the datatype property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDatatype(String value) {
                this.datatype = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="mesto" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="datum" type="{http://www.ftn.uns.ac.rs/zahtev}TDatum"/>
     *       &lt;/sequence>
     *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" fixed="http://www.ftn.uns.ac.rs/rdf/resenje/mestoDatumZahteva" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tekst",
        "mesto",
        "datum"
    })
    public static class MestoIDatum {

        @XmlElement(required = true)
        protected String tekst;
        @XmlElement(required = true)
        protected String mesto;
        @XmlElement(required = true)
        protected TDatum datum;
        @XmlAttribute(name = "about")
        @XmlSchemaType(name = "anySimpleType")
        protected String about;

        /**
         * Gets the value of the tekst property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTekst() {
            return tekst;
        }

        /**
         * Sets the value of the tekst property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTekst(String value) {
            this.tekst = value;
        }

        /**
         * Gets the value of the mesto property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMesto() {
            return mesto;
        }

        /**
         * Sets the value of the mesto property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMesto(String value) {
            this.mesto = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link TDatum }
         *     
         */
        public TDatum getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link TDatum }
         *     
         */
        public void setDatum(TDatum value) {
            this.datum = value;
        }

        /**
         * Gets the value of the about property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAbout() {
            if (about == null) {
                return "http://www.ftn.uns.ac.rs/rdf/resenje/mestoDatumZahteva";
            } else {
                return about;
            }
        }

        /**
         * Sets the value of the about property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAbout(String value) {
            this.about = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *         &lt;element name="tipovi_zahteva">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="tip_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="tip_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="tip_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="tip_zahteva_dostava">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
     *                             &lt;element name="vrste_dostave" type="{http://www.ftn.uns.ac.rs/zahtev}TDostava"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="informacije_o_zahtevu" type="{http://www.ftn.uns.ac.rs/zahtev}TInformacijeOZahtevu"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tekst",
        "tipoviZahteva",
        "informacijeOZahtevu"
    })
    public static class Sadrzaj {

        @XmlElement(required = true)
        protected Object tekst;
        @XmlElement(name = "tipovi_zahteva", required = true)
        protected ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Sadrzaj.TipoviZahteva tipoviZahteva;
        @XmlElement(name = "informacije_o_zahtevu", required = true)
        protected TInformacijeOZahtevu informacijeOZahtevu;

        /**
         * Gets the value of the tekst property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getTekst() {
            return tekst;
        }

        /**
         * Sets the value of the tekst property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setTekst(Object value) {
            this.tekst = value;
        }

        /**
         * Gets the value of the tipoviZahteva property.
         * 
         * @return
         *     possible object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Sadrzaj.TipoviZahteva }
         *     
         */
        public ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Sadrzaj.TipoviZahteva getTipoviZahteva() {
            return tipoviZahteva;
        }

        /**
         * Sets the value of the tipoviZahteva property.
         * 
         * @param value
         *     allowed object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Sadrzaj.TipoviZahteva }
         *     
         */
        public void setTipoviZahteva(ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Sadrzaj.TipoviZahteva value) {
            this.tipoviZahteva = value;
        }

        /**
         * Gets the value of the informacijeOZahtevu property.
         * 
         * @return
         *     possible object is
         *     {@link TInformacijeOZahtevu }
         *     
         */
        public TInformacijeOZahtevu getInformacijeOZahtevu() {
            return informacijeOZahtevu;
        }

        /**
         * Sets the value of the informacijeOZahtevu property.
         * 
         * @param value
         *     allowed object is
         *     {@link TInformacijeOZahtevu }
         *     
         */
        public void setInformacijeOZahtevu(TInformacijeOZahtevu value) {
            this.informacijeOZahtevu = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="tip_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="tip_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="tip_zahteva" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="tip_zahteva_dostava">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
         *                   &lt;element name="vrste_dostave" type="{http://www.ftn.uns.ac.rs/zahtev}TDostava"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "content"
        })
        public static class TipoviZahteva {

            @XmlElementRefs({
                @XmlElementRef(name = "tip_zahteva", namespace = "http://www.ftn.uns.ac.rs/zahtev", type = JAXBElement.class, required = false),
                @XmlElementRef(name = "tip_zahteva_dostava", namespace = "http://www.ftn.uns.ac.rs/zahtev", type = JAXBElement.class, required = false)
            })
            protected List<JAXBElement<?>> content;

            /**
             * Gets the rest of the content model. 
             * 
             * <p>
             * You are getting this "catch-all" property because of the following reason: 
             * The field name "TipZahteva" is used by two different parts of a schema. See: 
             * line 32 of file:/D:/Users/Hp%20Zbook%2015/Desktop/xml-projekat-2020/xml-documents/zahtev.xsd
             * line 31 of file:/D:/Users/Hp%20Zbook%2015/Desktop/xml-projekat-2020/xml-documents/zahtev.xsd
             * <p>
             * To get rid of this property, apply a property customization to one 
             * of both of the following declarations to change their names: 
             * Gets the value of the content property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the content property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getContent().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link JAXBElement }{@code <}{@link String }{@code >}
             * {@link JAXBElement }{@code <}{@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Sadrzaj.TipoviZahteva.TipZahtevaDostava }{@code >}
             * 
             * 
             */
            public List<JAXBElement<?>> getContent() {
                if (content == null) {
                    content = new ArrayList<JAXBElement<?>>();
                }
                return this.content;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="tekst" type="{http://www.w3.org/2001/XMLSchema}anyType"/>
             *         &lt;element name="vrste_dostave" type="{http://www.ftn.uns.ac.rs/zahtev}TDostava"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "tekst",
                "vrsteDostave"
            })
            public static class TipZahtevaDostava {

                @XmlElement(required = true)
                protected Object tekst;
                @XmlElement(name = "vrste_dostave", required = true)
                protected TDostava vrsteDostave;

                /**
                 * Gets the value of the tekst property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Object }
                 *     
                 */
                public Object getTekst() {
                    return tekst;
                }

                /**
                 * Sets the value of the tekst property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Object }
                 *     
                 */
                public void setTekst(Object value) {
                    this.tekst = value;
                }

                /**
                 * Gets the value of the vrsteDostave property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link TDostava }
                 *     
                 */
                public TDostava getVrsteDostave() {
                    return vrsteDostave;
                }

                /**
                 * Sets the value of the vrsteDostave property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link TDostava }
                 *     
                 */
                public void setVrsteDostave(TDostava value) {
                    this.vrsteDostave = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="organ">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="sediste_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "organ"
    })
    public static class Zaglavlje {

        @XmlElement(required = true)
        protected ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Zaglavlje.Organ organ;

        /**
         * Gets the value of the organ property.
         * 
         * @return
         *     possible object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Zaglavlje.Organ }
         *     
         */
        public ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Zaglavlje.Organ getOrgan() {
            return organ;
        }

        /**
         * Sets the value of the organ property.
         * 
         * @param value
         *     allowed object is
         *     {@link ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Zaglavlje.Organ }
         *     
         */
        public void setOrgan(ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama.Zaglavlje.Organ value) {
            this.organ = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="naziv_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="sediste_organa" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "nazivOrgana",
            "sedisteOrgana"
        })
        public static class Organ {

            @XmlElement(name = "naziv_organa", required = true)
            protected String nazivOrgana;
            @XmlElement(name = "sediste_organa", required = true)
            protected String sedisteOrgana;

            /**
             * Gets the value of the nazivOrgana property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getNazivOrgana() {
                return nazivOrgana;
            }

            /**
             * Sets the value of the nazivOrgana property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setNazivOrgana(String value) {
                this.nazivOrgana = value;
            }

            /**
             * Gets the value of the sedisteOrgana property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getSedisteOrgana() {
                return sedisteOrgana;
            }

            /**
             * Sets the value of the sedisteOrgana property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSedisteOrgana(String value) {
                this.sedisteOrgana = value;
            }

        }

    }

}
