//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.02.06 at 12:22:29 PM CET 
//


package ftn.xml.ServisOrganVlasti.soap.zahtev;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

import ftn.xml.ServisOrganVlasti.model.zahtev.ZahtevZaPristupInformacijama;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ftn.uns.ac.rs/zahtev}zahtev_za_pristup_informacijama"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zahtevZaPristupInformacijama"
})
@XmlRootElement(name = "getZahtevResponse")
public class GetZahtevResponse {

    @XmlElement(name = "zahtev_za_pristup_informacijama", namespace = "http://www.ftn.uns.ac.rs/zahtev", required = true)
    protected ZahtevZaPristupInformacijama zahtevZaPristupInformacijama;

    /**
     * Gets the value of the zahtevZaPristupInformacijama property.
     * 
     * @return
     *     possible object is
     *     {@link ZahtevZaPristupInformacijama }
     *     
     */
    public ZahtevZaPristupInformacijama getZahtevZaPristupInformacijama() {
        return zahtevZaPristupInformacijama;
    }

    /**
     * Sets the value of the zahtevZaPristupInformacijama property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZahtevZaPristupInformacijama }
     *     
     */
    public void setZahtevZaPristupInformacijama(ZahtevZaPristupInformacijama value) {
        this.zahtevZaPristupInformacijama = value;
    }

}
